apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap.yaml
  namespace: default
data:
  index.html: |
    <html>
    <head>
    <title>Hello World</title>
    </head>
    <body>
    <h1>Hello World!</h1>
    </body>
    </html>